### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by AndrewDaGuy** [AndrewDaGuy/Discord-AndrewDaBot#5]
```js
[Error: ENOENT: no such file or directory, scandir '\src\EventHandler\Events'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '\\src\\EventHandler\\Events'
}

\src\EventsHandler\EventHandler.js:9
        let jsfiles = files.filter(f => f.split(".").pop() === 'js');
                            ^

TypeError: Cannot read property 'filter' of undefined
    at \src\EventsHandler\EventHandler.js:9:29
    at FSReqCallback.oncomplete (fs.js:156:23)
```

**Comment by AndrewDaGuy** [comment]
Fixed on **Commit 20bb4b5**
